### ISSUE TITLE
Generated synonyms

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#195]
“orders {order_date|ORDER DATE}“,
“{order_date|ORDER DATE} <OF> orders”

Seems strange (repeated order, upper case)

**Comment by vic64** [comment]
Fixed in GH-190.

**Comment by skhdl** [comment]
is it in branch GH-190 ? 
if yes - did you check your changes?
    "id" : "orders.order_date",
    "groups" : [ "column" ],
    "synonyms" : [ 
"{orders|ORDERS} {order_date|order date}", 
"{order_date|order date} <OF> {orders|ORDERS}" ],

1) Why some synonyms are still in upper case ?
2) usual "order date" and "order_date" are still not represented as synonyms in generated synonyms list. 
(Now it should be 'orders order date', 'order date of orders' etc)

Please drop  this intelligent processing if it is difficult to provide at least "order date" and "order_date" as synonyms, just keep keep "order date" and "order_date" generated in synonyms list

**Comment by skhdl** [comment]
we still don't have 'order date' synonym

**Comment by vic64** [comment]
Fixed in GH-195. 

**NOTE:** 'order date' cannot be a synonym as 'order_date' is not a unique column.

**Comment by skhdl** [comment]
`order date` should be supported (It should be fixed after GH-198)

**Comment by vic64** [comment]
Fixed in `release`.
